services:
  - type: web
    name: sr-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://sr-backend-im3y.onrender.com/api/v1
