export const SONGS_DATA = [
  {
    id: 1,
    title: 'Midnight City',
    artist: 'M83',
    key: 'C#m',
    bpm: 105,
    duration: '4:03',
    eligibility: 'High',
    requester: 'Alice',
    requestCount: 2,
  },
  {
    id: 2,
    title: 'Get Lucky',
    artist: 'Daft Punk',
    key: 'F#m',
    bpm: 116,
    duration: '4:08',
    eligibility: 'High',
    requester: 'Bob',
    requestCount: 8,
  },
  {
    id: 3,
    title: 'Levels',
    artist: 'Avicii',
    key: 'C#m',
    bpm: 126,
    duration: '3:19',
    eligibility: 'Medium',
    requester: 'Charlie',
    requestCount: 1,
  },
  {
    id: 4,
    title: 'Titanium',
    artist: 'David Guetta',
    key: 'Cm',
    bpm: 126,
    duration: '4:05',
    eligibility: 'High',
    requester: 'Dave',
    requestCount: 12,
  },
  {
    id: 5,
    title: 'Wake Me Up',
    artist: 'Avicii',
    key: 'Bm',
    bpm: 124,
    duration: '4:07',
    eligibility: 'Low',
    requester: 'Eve',
    requestCount: 5,
  },
] as const;

export const FREQUENT_REQUEST_THRESHOLD = 5;
